import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import { AuthLayout, RootLayout } from '@/components/Layouts';
import { HomePageContainer } from '@/containers/Home';
import { wrapper } from '@/store';
import { authApi } from '@/store/api/authApi';
import { subjectApi } from '@/store/api/subjectApi';
import { commonApi } from '@/store/config/commonApi';

const Home: NextPage = () => (
  <RootLayout>
    <AuthLayout pagePermission='common'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HomePageContainer />
    </AuthLayout>
  </RootLayout>
);

export default Home;

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(store => async context => {
  store.dispatch(authApi.endpoints.checkAuth.initiate());
  store.dispatch(subjectApi.endpoints.getSubjects.initiate());

  await Promise.all(store.dispatch(commonApi.util.getRunningQueriesThunk()));
  // console.dir(store.getState().commonApi, { depth: Infinity });

  return {
    props: {},
  };
});
